#pragma once

#ifndef TEXTURES_AANG
#define TEXTURES_AANF

#include <glad/glad.h>

float TEX_AANG_WIDTH = 2048.0f;
float TEX_AANG_HEIGHT = 2048.0f;
float TEX_FIRE_WIDTH = 32.0f;
float TEX_FIRE_HEIGHT = 32.0f;
float PIXEL_SIZE_AANG = 23.0f;

GLfloat headAangTextureCoordsBuffer[72];
GLfloat bodyAangTextureCoordsBuffer[72];
GLfloat earAangTextureCoordsBuffer[72];
GLfloat armAangTextureCoordsBuffer[72];
GLfloat legAangTextureCoordsBuffer[72];
GLfloat shoeAangTextureCoordsBuffer[72];
GLfloat shoeUpAangTextureCoordsBuffer[72];
GLfloat FireAangTextureCoordsBuffer[72];
GLfloat WaterAangTextureCoordsBuffer[72];

void loadTextureDataAang() {

	GLfloat headAangTextureCoords[72] = {
		//Cara
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),

		//Nuca
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 368.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 368.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 368.0f) / TEX_AANG_HEIGHT),

		//Izq
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),

		//der
		(1104.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(1104.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),
		(1104.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),

		//Up
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 736.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1104.0f) / TEX_AANG_HEIGHT),


		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 368.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 0.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 0.0f) / TEX_AANG_HEIGHT),
		(368.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 368.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 0.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 368.0f) / TEX_AANG_HEIGHT),
	};

	GLfloat bodyAangTextureCoords[72] = {
		//Frente
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(276.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(276.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1495.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1495.0f) / TEX_AANG_HEIGHT),
		(276.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1495.0f) / TEX_AANG_HEIGHT),

		//Espalda
		(460.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1495.0f) / TEX_AANG_HEIGHT),
		(460.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(460.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1495.0f) / TEX_AANG_HEIGHT),
		(736.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1495.0f) / TEX_AANG_HEIGHT),

		//Izq
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1127.0f) / TEX_AANG_HEIGHT),
		(92.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1127.0f) / TEX_AANG_HEIGHT),
		(92.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(92.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1127.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),

		//der
		(437.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1495.0f) / TEX_AANG_HEIGHT),
		(437.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(345.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(437.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1495.0f) / TEX_AANG_HEIGHT),
		(345.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1495.0f) / TEX_AANG_HEIGHT),
		(345.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),

		//Up
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1128.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1128.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1128.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1128.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1128.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1128.0f) / TEX_AANG_HEIGHT),

		//Down
		(460.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(460.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1817.0f) / TEX_AANG_HEIGHT),
		(483.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1817.0f) / TEX_AANG_HEIGHT),
		(460.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(483.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1817.0f) / TEX_AANG_HEIGHT),
		(483.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
	};

	GLfloat earAangTextureCoords[72] = {
		//Frente
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(0.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),

		//Espalda
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(92.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(92.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(92.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),

		//Izq
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),

		//der
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),

		//Up
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 0.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 0.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 0.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 23.0f) / TEX_AANG_HEIGHT),

		//Down
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 138.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(23.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 138.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 115.0f) / TEX_AANG_HEIGHT),
		(69.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 138.0f) / TEX_AANG_HEIGHT),
	};

	GLfloat armAangTextureCoords[72] = {
		//Frente
		(115.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(115.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(115.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),

		//Espalda
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(253.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(253.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(253.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),

		//Izq
		(253.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(299.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(299.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(299.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(253.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(253.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),

		//der
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),

		//Up
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 0.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 0.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 0.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 46.0f) / TEX_AANG_HEIGHT),

		//Down
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 253.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 253.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 253.0f) / TEX_AANG_HEIGHT),
		(161.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
		(207.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 207.0f) / TEX_AANG_HEIGHT),
	};

	GLfloat legAangTextureCoords[72] = {
		//Frente
		(782.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1702.0f) / TEX_AANG_HEIGHT),
		(874.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1702.0f) / TEX_AANG_HEIGHT),
		(874.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(782.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1702.0f) / TEX_AANG_HEIGHT),
		(782.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(874.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),

		//Espalda
		(943.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(1035.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(1035.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1219.0f) / TEX_AANG_HEIGHT),
		(943.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(943.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1219.0f) / TEX_AANG_HEIGHT),
		(1035.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1219.0f) / TEX_AANG_HEIGHT),

		//Izq
		(1057.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1220.0f) / TEX_AANG_HEIGHT),
		(1149.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1220.0f) / TEX_AANG_HEIGHT),
		(1149.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(1149.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(1057.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1220.0f) / TEX_AANG_HEIGHT),
		(1057.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),

		//der
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1702.0f) / TEX_AANG_HEIGHT),
		(1058.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1702.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(1058.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1472.0f) / TEX_AANG_HEIGHT),
		(1058.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1702.0f) / TEX_AANG_HEIGHT),

		//Up
		(460.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(460.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1817.0f) / TEX_AANG_HEIGHT),
		(483.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1817.0f) / TEX_AANG_HEIGHT),
		(460.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		(483.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1817.0f) / TEX_AANG_HEIGHT),
		(483.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1840.0f) / TEX_AANG_HEIGHT),
		
		//Down
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
	};

	GLfloat shoeAangTextureCoords[72] = {
		//Frente
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),

		//Espalda
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),

		//Izq
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),

		//der
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),

		//Up
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),

		//Down
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
		(759.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1357.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1449.0f) / TEX_AANG_HEIGHT),
	};

	GLfloat shoeUpAangTextureCoords[72] = {
		//Frente
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),

		//Espalda
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),

		//Izq
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),

		//der
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),

		//Up
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),

		//Down
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1656.0f) / TEX_AANG_HEIGHT),
		(920.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
		(966.0f / TEX_AANG_WIDTH), ((TEX_AANG_HEIGHT - 1633.0f) / TEX_AANG_HEIGHT),
	};

	GLfloat FireAangTextureCoords[72] = {
		//Frente
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),

		//Espalda
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),

		//Izq
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),

		//der
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),

		//Up
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),

		//Down
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
	};

	GLfloat WaterAangTextureCoords[72] = {
		//Frente
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),

		//Espalda
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),

		//Izq
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),

		//der
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(160.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 32.0f) / TEX_FIRE_HEIGHT),

		//Up
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),

		//Down
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
		(0.0f / TEX_FIRE_WIDTH), ((TEX_FIRE_HEIGHT - 0.0f) / TEX_FIRE_HEIGHT),
	};

	for (int i = 0; i < 72; i++) {
		headAangTextureCoordsBuffer[i] = headAangTextureCoords[i];
		bodyAangTextureCoordsBuffer[i] = bodyAangTextureCoords[i];
		earAangTextureCoordsBuffer[i] = earAangTextureCoords[i];
		armAangTextureCoordsBuffer[i] = armAangTextureCoords[i];
		legAangTextureCoordsBuffer[i] = legAangTextureCoords[i];
		shoeAangTextureCoordsBuffer[i] = shoeAangTextureCoords[i];
		shoeUpAangTextureCoordsBuffer[i] = shoeUpAangTextureCoords[i];
		FireAangTextureCoordsBuffer[i] = FireAangTextureCoords[i];
		WaterAangTextureCoordsBuffer[i] = WaterAangTextureCoords[i];
	}
}

#endif // !

